package com.nammashale.shalepride.util

import android.content.Context
import android.graphics.*
import android.graphics.pdf.PdfDocument
import android.os.Environment
import com.nammashale.shalepride.data.model.Feedback
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*

/**
 * Generates styled PDF reports using Android's built-in PdfDocument API.
 * No external library needed.
 */
object PdfReportGenerator {

    private const val PAGE_WIDTH = 595   // A4 width in points (72 dpi)
    private const val PAGE_HEIGHT = 842  // A4 height in points
    private const val MARGIN = 48f
    private const val LINE_HEIGHT = 22f

    data class ReportData(
        val mealCount: Int = 0,
        val postCount: Int = 0,
        val starCount: Int = 0,
        val feedbackCount: Int = 0,
        val feedbackList: List<Feedback> = emptyList()
    )

    fun generateSchoolSummaryReport(context: Context, data: ReportData): File? {
        return try {
            val doc = PdfDocument()
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, 1).create()
            val page = doc.startPage(pageInfo)
            val canvas = page.canvas
            var y = drawHeader(canvas, "SHALE-NAMMA PRIDE", "School Summary Report")

            y = drawSectionTitle(canvas, y, "📊 Statistics Overview")
            y = drawStatRow(canvas, y, "Total Meals Uploaded", data.mealCount.toString())
            y = drawStatRow(canvas, y, "Total Posts / Activities", data.postCount.toString())
            y = drawStatRow(canvas, y, "Student Stars Awarded", data.starCount.toString())
            y = drawStatRow(canvas, y, "Parent Feedback Received", data.feedbackCount.toString())

            y = drawSectionTitle(canvas, y + LINE_HEIGHT, "📅 Report Generated")
            y = drawStatRow(canvas, y, "Date & Time", SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault()).format(Date()))
            y = drawStatRow(canvas, y, "Generated By", "School Administrator")

            drawFooter(canvas)
            doc.finishPage(page)

            val file = saveToFile(context, doc, "school_summary_report")
            doc.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    fun generateFeedbackReport(context: Context, feedbackList: List<Feedback>): File? {
        return try {
            val doc = PdfDocument()
            var pageNum = 1
            var pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
            var page = doc.startPage(pageInfo)
            var canvas = page.canvas
            var y = drawHeader(canvas, "SHALE-NAMMA PRIDE", "Parent Feedback Report")

            val positive = feedbackList.count { it.sentiment == SentimentAnalyzer.POSITIVE }
            val negative = feedbackList.count { it.sentiment == SentimentAnalyzer.NEGATIVE }
            val neutral = feedbackList.count { it.sentiment == SentimentAnalyzer.NEUTRAL }

            y = drawSectionTitle(canvas, y, "📊 Sentiment Summary")
            y = drawStatRow(canvas, y, "🟢 Positive Feedback", positive.toString())
            y = drawStatRow(canvas, y, "🟡 Neutral Feedback", neutral.toString())
            y = drawStatRow(canvas, y, "🔴 Negative Feedback", negative.toString())
            y = drawStatRow(canvas, y, "Total Feedback", feedbackList.size.toString())
            y += LINE_HEIGHT

            y = drawSectionTitle(canvas, y, "📝 All Feedback Messages")

            val textPaint = Paint().apply {
                color = Color.parseColor("#333333")
                textSize = 11f
                typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL)
                isAntiAlias = true
            }
            val hintPaint = Paint().apply {
                color = Color.parseColor("#888888")
                textSize = 9f
                isAntiAlias = true
            }

            for ((index, fb) in feedbackList.withIndex()) {
                // Check if we need a new page
                if (y > PAGE_HEIGHT - 120) {
                    drawFooter(canvas)
                    doc.finishPage(page)
                    pageNum++
                    pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNum).create()
                    page = doc.startPage(pageInfo)
                    canvas = page.canvas
                    y = MARGIN + 20f
                }

                // Draw feedback item box
                val boxPaint = Paint().apply {
                    color = when (fb.sentiment) {
                        SentimentAnalyzer.POSITIVE -> Color.parseColor("#F1FFF5")
                        SentimentAnalyzer.NEGATIVE -> Color.parseColor("#FFF5F5")
                        else -> Color.parseColor("#FFFDF0")
                    }
                    style = Paint.Style.FILL
                }
                val rect = RectF(MARGIN, y, PAGE_WIDTH - MARGIN, y + 60f)
                canvas.drawRoundRect(rect, 8f, 8f, boxPaint)

                val senderName = if (fb.isAnonymous) "Anonymous Parent" else fb.senderName.ifBlank { "Parent" }
                val sentiment = "${SentimentAnalyzer.getEmoji(fb.sentiment)} ${SentimentAnalyzer.getLabel(fb.sentiment)}"
                val dateStr = SimpleDateFormat("dd MMM yyyy", Locale.getDefault()).format(Date(fb.timestamp))

                canvas.drawText("${index + 1}. $senderName  |  $sentiment  |  $dateStr", MARGIN + 8f, y + 16f, hintPaint)
                canvas.drawText(fb.message.take(100) + if (fb.message.length > 100) "..." else "", MARGIN + 8f, y + 34f, textPaint)

                y += 70f
            }

            drawFooter(canvas)
            doc.finishPage(page)

            val file = saveToFile(context, doc, "feedback_report")
            doc.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            null
        }
    }

    // ─── Private Drawing Helpers ──────────────────────────────────────────────

    private fun drawHeader(canvas: Canvas, title: String, subtitle: String): Float {
        // Header background
        val headerPaint = Paint().apply {
            color = Color.parseColor("#1E6B3C")
            style = Paint.Style.FILL
        }
        canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), 90f, headerPaint)

        // School name
        val titlePaint = Paint().apply {
            color = Color.WHITE
            textSize = 20f
            typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
            isAntiAlias = true
        }
        canvas.drawText(title, MARGIN, 40f, titlePaint)

        // Subtitle
        val subPaint = Paint().apply {
            color = Color.parseColor("#BBFFFFFF")
            textSize = 12f
            isAntiAlias = true
        }
        canvas.drawText(subtitle, MARGIN, 62f, subPaint)

        // Divider line
        val linePaint = Paint().apply {
            color = Color.parseColor("#4CAF50")
            strokeWidth = 3f
        }
        canvas.drawLine(0f, 90f, PAGE_WIDTH.toFloat(), 90f, linePaint)

        return 120f
    }

    private fun drawSectionTitle(canvas: Canvas, y: Float, title: String): Float {
        val paint = Paint().apply {
            color = Color.parseColor("#1E6B3C")
            textSize = 13f
            typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
            isAntiAlias = true
        }
        canvas.drawText(title, MARGIN, y, paint)
        val linePaint = Paint().apply {
            color = Color.parseColor("#DDDDDD")
            strokeWidth = 1f
        }
        canvas.drawLine(MARGIN, y + 6f, PAGE_WIDTH - MARGIN, y + 6f, linePaint)
        return y + LINE_HEIGHT + 4f
    }

    private fun drawStatRow(canvas: Canvas, y: Float, label: String, value: String): Float {
        val labelPaint = Paint().apply {
            color = Color.parseColor("#555555")
            textSize = 11f
            isAntiAlias = true
        }
        val valuePaint = Paint().apply {
            color = Color.parseColor("#111111")
            textSize = 11f
            typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
            isAntiAlias = true
        }
        canvas.drawText(label, MARGIN, y, labelPaint)
        canvas.drawText(value, PAGE_WIDTH - MARGIN - valuePaint.measureText(value), y, valuePaint)
        return y + LINE_HEIGHT
    }

    private fun drawFooter(canvas: Canvas) {
        val footerPaint = Paint().apply {
            color = Color.parseColor("#EEEEEE")
            style = Paint.Style.FILL
        }
        canvas.drawRect(0f, PAGE_HEIGHT - 40f, PAGE_WIDTH.toFloat(), PAGE_HEIGHT.toFloat(), footerPaint)

        val textPaint = Paint().apply {
            color = Color.parseColor("#888888")
            textSize = 9f
            isAntiAlias = true
        }
        canvas.drawText("Shale-Namma Pride | Government School Transparency Portal", MARGIN, PAGE_HEIGHT - 22f, textPaint)
        val date = SimpleDateFormat("dd/MM/yyyy", Locale.getDefault()).format(Date())
        canvas.drawText("Generated: $date", PAGE_WIDTH - MARGIN - 80f, PAGE_HEIGHT - 22f, textPaint)
    }

    private fun saveToFile(context: Context, doc: PdfDocument, name: String): File {
        val dir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
            ?: context.filesDir
        dir.mkdirs()
        val timestamp = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.getDefault()).format(Date())
        val file = File(dir, "${name}_$timestamp.pdf")
        FileOutputStream(file).use { doc.writeTo(it) }
        return file
    }
}
